# Generated by Django 5.2.4 on 2025-08-15 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_category_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='group_slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
