version: "3.9"

services:
  db:
    image: postgres:14
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env.local

  django-web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    depends_on:
      - db
    volumes:
      - .:/app
      - ./static:/app/staticfiles
    ports:
      - "8000:8000"
    env_file:
      - .env.local

volumes:
  postgres_data:
